#Create a new set
num_set = set([2,4,6,8,5,10,15,20,25,30])
print("Original set elements:")
print(num_set)
print("\nRemove 2 from the said set:")
num_set.discard(4)
print(num_set)
print("\nRemove 6 from the said set:")
num_set.discard(5)
print(num_set)
print("\nRemove 10 from the said set:")
num_set.discard(5)
print(num_set)
print("\nRemove 30 from the said set:")
num_set.discard(15)
print(num_set)